WebStore.WebUI/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebStore.Domain.Entities;
using WebStore.WebUI.Domain;
using WebStore.WebUI.Domain.Entities;
using WebStore.WebUI.Models;

namespace WebStore.WebUI.Controllers
{
    public class CartController : Controller
    {
        private GameRepository gameRepository;
        public CartController()
        {
            gameRepository = new GameRepository();
            gameRepository.RepositoryInit();
        }

        public ViewResult Index(Cart cart, string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                User = (User)Session["User"],
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }

        public RedirectToRouteResult AddToCart(Cart cart, int gameId, string returnUrl)
        {
            Game game = gameRepository.games
                .FirstOrDefault(g => g.GameID == gameId);

            if (game != null)
            {
                cart.AddItem(game, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart, int gameId, string returnUrl)
        {
            Game game = gameRepository.games
                .FirstOrDefault(g => g.GameID == gameId);

            if (game != null)
            {
                cart.RemoveLine(game);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }

        public ViewResult Checkout(Cart cart)
        {
            if (Session["User"] as User == null)
                return null;
            DatabaseRelation.MakeOrder(cart, (User)Session["User"]);
            cart.Clear();
            return View();
        }

        [HttpGet]
        public ActionResult LoginForm()
        {
            return View("~/Views/Game/LoginForm.cshtml");
        }

        [HttpGet]
        public ActionResult RegisterForm()
        {
            return View("~/Views/Game/RegisterForm.cshtml");
        }
    }
}

WebStore.WebUI/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;
using WebStore.Domain.Entities;
using WebStore.WebUI.Domain;
using WebStore.WebUI.Domain.Entities;
using WebStore.WebUI.Models;

namespace WebStore.WebUI.Controllers
{
    public class GameController : Controller
    {
        public GameRepository gameRepository;
        public int pageSize = 8;

        public GameController()
        {
            gameRepository = new GameRepository();
            gameRepository.RepositoryInit();
        }

        public ViewResult List(string category, int page = 1)
        {
            GamesListViewModel model = new GamesListViewModel
            {
                Games = DatabaseRelation.getGames()
                    .Where(p => category == null || p.Category == category)
                    .OrderBy(game => game.GameID)
                    .Skip((page - 1) * pageSize)
                    .Take(pageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = category == null ?
                gameRepository.games.Count() :
                gameRepository.games.Where(game => game.Category == category).Count()
                },
                CurrentCategory = category
            };
            return View(model);
        }

        [HttpGet]
        public ActionResult LoginForm()
        {
            return View();
        }

        [HttpPost]
        public ViewResult LoginForm(LoginForm client)
        {
            if (ModelState.IsValid)
            {
                if (client != null)
                {
                    User u = DatabaseRelation.logIn(client);
                    if (u != null)
                    {
                        Session["User"] = u;
                        return View("Welcome", u);
                    }
                    else return View();
                }
                else return View("Index");
            }
            else return View();
        }

        [HttpGet]
        public ActionResult RegisterForm()
        {
            return View();
        }

        [HttpPost]
        public ViewResult RegisterForm(RegisterForm client)
        {
            if (ModelState.IsValid)
            {
                if (client != null)
                {
                    DatabaseRelation.RegisterUser(client);
                    return View();
                }
                else return View("Index");
            }
            else return View();
        }

        public PartialViewResult LoginRegisterForm()
        {
            User user = (User)Session["User"];
            if(user == null)
                return PartialView();
            else
                if (user.Admin == 1)
                return PartialView("AdminController", user);
            else
                return PartialView("UserController", user);
        }

        [HttpGet]
        public RedirectToRouteResult LogOut()
        {
            Session["User"] = null;
            return RedirectToAction("LoginForm");
        }
    }
}

WebStore.WebUI/Views/Cart/Checkout.cshtml
@model WebStore.WebUI.Domain.Entities.ShippingDetails

@{
    ViewBag.Title = "GameStore: order form";
}

<h2>Thanks for the order!</h2>

WebStore.WebUI/Views/Cart/Index.cshtml
@model WebStore.WebUI.Models.CartIndexViewModel

@{
    ViewBag.Title = "GameStore: Your Cart";
}

<style>
    #cartTable td {
        vertical-align: middle;
    }
</style>

<h2>Your Cart</h2>
<table id="cartTable" class="table">
    <thead>
        <tr>
            <th>Count</th>
            <th>Game</th>
            <th class="text-right">Price</th>
            <th class="text-right">Total price</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var line in Model.Cart.Lines)
        {
            <tr>
                <td class="text-center">@line.quantity</td>
                <td class="text-left">@line.game.Name</td>
                <td class="text-right">@line.game.Price.ToString("$#")</td>
                <td class="text-right">
                    @((line.quantity * line.game.Price).ToString("$#"))
                </td>
                <td>
                    @using (Html.BeginForm("RemoveFromCart", "Cart"))
                    {
                        @Html.Hidden("GameId", line.game.GameID)
                        @Html.HiddenFor(x => x.ReturnUrl)
                        <input class="btn delete" type="submit" value="Delete" />
                    }
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Total:</td>
            <td class="text-right">
                @Model.Cart.ComputeTotalValue().ToString("$#")
            </td>
        </tr>
    </tfoot>
</table>

<div class="text-center">
    <a class="btn btn-primary" href="@Model.ReturnUrl">Continue Shopping</a>
    @if (Model.User == null)
    {
        @Html.ActionLink("Login", "LoginForm", "Game",
        new { @class = "btn" })
    }
    else
    {
        if (Model.Cart.Lines.Count() > 0)
        {
        @Html.ActionLink("Checkout", "Checkout", null, new { @class = "btn btn-primary" });
        }
    }
</div>

WebStore.WebUI/Views/Cart/Summary.cshtml
@model WebStore.WebUI.Domain.Entities.Cart

<div class="barContRight">
    <div class="barCont">
        <b>In Cart:</b>
        @Model.Lines.Sum(x => x.quantity) games,
        @Model.ComputeTotalValue().ToString("$#")
    </div>

    <div class="barCont">
        @Html.ActionLink("Order", "Index", "Cart",
        new { returnUrl = Request.Url.PathAndQuery },
        new { @class = "btn" })
    </div>
</div>