WebStore.WebUI/Controllers/AdminPanelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebStore.Domain.Entities;
using WebStore.WebUI.Domain;
using WebStore.WebUI.Domain.Entities;
using WebStore.WebUI.Models;

namespace WebStore.WebUI.Controllers
{
    public class AdminPanelController : Controller
    {
        public GameRepository gameRepository;
        public AdminPanelController()
        {
            gameRepository = new GameRepository();
            gameRepository.RepositoryInit();
        }

        public bool AdminCheck()
        {
            User user = (User)Session["User"];
            if (user == null)
                return false;
            if(user.Admin == 0)
                return false;
            return true;
        }

        public ActionResult Index()
        {
            if (!AdminCheck())
                return View("Index");
            return View();
        }

        public ActionResult EditPage()
        {
            if (!AdminCheck())
                return View("Index");
            GamesListViewModel model = new GamesListViewModel
            {
                Games = DatabaseRelation.getGames()
        .OrderBy(game => game.GameID)
            };
            return View(model);
        }

        public ActionResult Edit(int gameId)
        {
            if (!AdminCheck())
                return View("Index");
            Game game = new Game();
            foreach(Game g in DatabaseRelation.getGames())
            {
                if (g.GameID == gameId)
                    game = g;
            }
            return View(game);
        }

        public ActionResult AddPage()
        {
            if (!AdminCheck())
                return View("Index");
            return View();
        }

        [HttpPost]
        public ViewResult EditGame(Game game)
        {
            GamesListViewModel model = new GamesListViewModel
            {
                Games = DatabaseRelation.getGames()
                .OrderBy(gm => gm.GameID)
            };
            if (ModelState.IsValid)
            {
                if (game != null)
                {
                    DatabaseRelation.EditGame(game);
                    model = new GamesListViewModel
                    {
                        Games = DatabaseRelation.getGames()
                        .OrderBy(gm => gm.GameID)
                    };
                    return View("EditPage", model);
                }
                else return View("Index");
            }
            else return View("Index");
        }

        [HttpPost]
        public ViewResult AddGame(Game game)
        {
            if (ModelState.IsValid)
            {
                if (game != null)
                {
                    DatabaseRelation.AddGame(game);
                    GamesListViewModel model = new GamesListViewModel
                    {
                        Games = DatabaseRelation.getGames()
                        .OrderBy(gm => gm.GameID)
                    };
                    return View("EditPage", model);
                }
                else return View("Index");
            }
            else return View("Index");
        }

        public RedirectToRouteResult DeleteGame(int gameId)
        {
            DatabaseRelation.DeleteGame(gameId);
            GamesListViewModel model = new GamesListViewModel
            {
                Games = DatabaseRelation.getGames()
                .OrderBy(gm => gm.GameID)
            };
            return RedirectToAction("EditPage", model);
        }

        [HttpGet]
        public ActionResult OrdersPage()
        {
            return View(DatabaseRelation.getOrders());
        }
    }
}

WebStore.WebUI/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;
using WebStore.Domain.Entities;
using WebStore.WebUI.Domain;
using WebStore.WebUI.Domain.Entities;
using WebStore.WebUI.Models;

namespace WebStore.WebUI.Controllers
{
    public class GameController : Controller
    {
        public GameRepository gameRepository;
        public int pageSize = 8;

        public GameController()
        {
            gameRepository = new GameRepository();
            gameRepository.RepositoryInit();
        }

        public ViewResult List(string category, int page = 1)
        {
            GamesListViewModel model = new GamesListViewModel
            {
                Games = DatabaseRelation.getGames()
                    .Where(p => category == null || p.Category == category)
                    .OrderBy(game => game.GameID)
                    .Skip((page - 1) * pageSize)
                    .Take(pageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = category == null ?
                gameRepository.games.Count() :
                gameRepository.games.Where(game => game.Category == category).Count()
                },
                CurrentCategory = category
            };
            return View(model);
        }

        [HttpGet]
        public ActionResult LoginForm()
        {
            return View();
        }

        [HttpPost]
        public ViewResult LoginForm(LoginForm client)
        {
            if (ModelState.IsValid)
            {
                if (client != null)
                {
                    User u = DatabaseRelation.logIn(client);
                    if (u != null)
                    {
                        Session["User"] = u;
                        return View("Welcome", u);
                    }
                    else return View();
                }
                else return View("Index");
            }
            else return View();
        }

        [HttpGet]
        public ActionResult RegisterForm()
        {
            return View();
        }

        [HttpPost]
        public ViewResult RegisterForm(RegisterForm client)
        {
            if (ModelState.IsValid)
            {
                if (client != null)
                {
                    DatabaseRelation.RegisterUser(client);
                    return View();
                }
                else return View("Index");
            }
            else return View();
        }

        public PartialViewResult LoginRegisterForm()
        {
            User user = (User)Session["User"];
            if(user == null)
                return PartialView();
            else
                if (user.Admin == 1)
                return PartialView("AdminController", user);
            else
                return PartialView("UserController", user);
        }

        [HttpGet]
        public RedirectToRouteResult LogOut()
        {
            Session["User"] = null;
            return RedirectToAction("LoginForm");
        }
    }
}

WebStore.WebUI/Views/Game/AdminController.cshtml
@model WebStore.WebUI.Domain.Entities.User

Hello, admin! - @Model.Name
@Html.ActionLink("Admin Panel", "Index", "AdminPanel",
new { returnUrl = Request.Url.PathAndQuery },
new { @class = "btn" })
@Html.ActionLink("LogOut", "LogOut", "Game",
new { @class = "btn" })

WebStore.WebUI/Views/Game/List.cshtml
@using WebStore.WebUI.Models
@using WebStore.WebUI.HtmlHelpers
@model GamesListViewModel

@{
    ViewBag.Title = "Goods";
}

@foreach (var p in @Model.Games)
{
    @Html.Partial("GameSummary", p)
}

<div class="btn-group pull-right">
    @Html.PageLinks(Model.PagingInfo, x => Url.Action("List",
        new { page = x, category = Model.CurrentCategory }))
</div>

WebStore.WebUI/Views/Game/LoginForm.cshtml
@model WebStore.WebUI.LoginForm

@{
    ViewBag.Title = "LogIn";
}

@using (Html.BeginForm())
{
    @Html.ValidationSummary()
    <div class="form-group">
        <label>Login:</label>
        @Html.TextBoxFor(x => x.Login, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Password:</label>
        @Html.PasswordFor(x => x.Password, new { @class = "form-control" })
    </div>
    <div class="text-center">
        <input type="submit" value="Login" class="btn btn-success" />
    </div>
}

WebStore.WebUI/Views/Game/LoginRegisterForm.cshtml
@Html.ActionLink("Login", "LoginForm", "Game",
new { @class = "btn" })
@Html.ActionLink("Register", "RegisterForm", "Game",
new { @class = "btn" })

WebStore.WebUI/Views/Game/RegisterForm.cshtml
@model WebStore.WebUI.RegisterForm

@{
    ViewBag.Title = "Register";
}

@using (Html.BeginForm())
{
    @Html.ValidationSummary()
    <div class="form-group">
        <label>Login:</label>
        @Html.TextBoxFor(x => x.Login, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Password:</label>
        @Html.PasswordFor(x => x.Password, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Name:</label>
        @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Surname:</label>
        @Html.TextBoxFor(x => x.Surname, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Patronymic:</label>
        @Html.TextBoxFor(x => x.Patronymic, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Phone:</label>
        @Html.TextBoxFor(x => x.Phone, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Mail:</label>
        @Html.TextBoxFor(x => x.Mail, new { @class = "form-control" })
    </div>
    <div class="text-center">
        <input type="submit" value="Register" class="btn btn-success" />
    </div>
}

WebStore.WebUI/Views/Game/UserController.cshtml
@model WebStore.WebUI.Domain.Entities.User

Hello, @Model.Name!
@Html.ActionLink("LogOut", "LogOut", "Game",
new { @class = "btn" })

WebStore.WebUI/Views/Game/Welcome.cshtml
@model WebStore.WebUI.Domain.Entities.User

<h2>Welcome, @Model.Name!</h2>